services:
  tts-api:
    build:
      context: .
      dockerfile: ./docker/tts/Dockerfile
    container_name: tts-fastapi
    init: true
    ports:
      - "8000:8000"
    volumes:
      # 개발 모드: 소스 코드 실시간 반영 (주석 해제)
      # - ./src/tts:/app/tts
      # 프로덕션 모드: 데이터 볼륨만 마운트
      - data-volume:/app/data
    networks:
      - moriai-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      nginx:
        condition: service_started
    restart: unless-stopped

  storybook-api:
    build:
      context: .
      dockerfile: ./docker/storybook/Dockerfile
    container_name: storybook-fastapi
    init: true
    ports:
      - "8001:8001"
    volumes:
      - storybook-data:/app/storybook
      - data-volume:/app/data
    environment:
      - TTS_API_URL=http://tts-api:8000
    networks:
      - moriai-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      nginx:
        condition: service_started
    restart: unless-stopped

  frontend-builder:
    build:
      context: ./src/front
      dockerfile: ../../docker/front/Dockerfile
    container_name: frontend-builder
    volumes:
      - ./src/front:/app
      - /app/node_modules
    networks:
      - moriai-network
    restart: "no"

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/front/dist:/usr/share/nginx/html:ro
      - ./data:/data:ro
    networks:
      - moriai-network
    depends_on:
      frontend-builder:
        condition: service_completed_successfully
    restart: unless-stopped

networks:
  moriai-network:
    driver: bridge

volumes:
  tts-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./src/tts
  storybook-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./src/storybook
  data-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
