services:
  tts-api:
    build:
      context: .
      dockerfile: ./docker/tts/Dockerfile
    container_name: tts-fastapi
    init: true
    ports:
      - "8000:8000"
    volumes:
      - tts-data:/app/tts
      - sound-data:/app/sound
    networks:
      - tts-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  tts-network:
    driver: bridge

volumes:
  tts-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./tts
  sound-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/sound
